///*
// * This source file was generated by the Gradle 'init' task
// */
//package io.github.gleidsonmt.todo;
//
//import io.github.gleidsonmt.todo.model.ToDoTask;
//import io.github.gleidsonmt.todo.model.recurrence.*;
//import org.junit.jupiter.api.Test;
//
//import java.time.DayOfWeek;
//import java.time.LocalDate;
//import java.util.*;
//
//class RecurrenceTests {
//    @Test
//    void appHasAGreeting() {
//
//    }
//
//    @Test
//    void verify_rec_daily() {
//
//        ToDoTask task = new ToDoTask(1, "Practice on my guitar", LocalDate.now().minusDays(1));
//
//        Daily daily = new Daily(1, 1, 1, new TreeSet<>(List.of(DayOfWeek.THURSDAY, DayOfWeek.WEDNESDAY)));
//        daily.setTaskID(task.getId());
//
//        LocalDate adjustGap = adjustGap(daily.getType(), task.getDueDate(), daily.getGap());
//        System.out.println("adjustGap = " + adjustGap);
//        LocalDate adjustWeekDay = adjustDays(adjustGap, daily.getDaysOfWeek());
//        System.out.println("nextDay = " + adjustWeekDay);
//
//    }
//
//    @Test
//    void verify_rec_weekdays() {
//        ToDoTask task = new ToDoTask(1, "Practice on my guitar", LocalDate.now().minusDays(1));
//
//        Weekly daily = new Weekly(1, 1, 1, true, new TreeSet<>(List.of( DayOfWeek.FRIDAY)));
//        daily.setTaskID(task.getId());
//
//        LocalDate adjustGap = adjustGap(daily.getType(), task.getDueDate(), daily.getGap());
//        System.out.println("adjustGap = " + adjustGap);
//        LocalDate adjustWeekDay = adjustDays(adjustGap, daily.getDaysOfWeek());
//        System.out.println("nextDay = " + adjustWeekDay);
//    }
//
//    @Test
//    void verify_rec_weekly() {
//        ToDoTask task = new ToDoTask(1, "Practice on my guitar", LocalDate.now().minusWeeks(1));
//        System.out.println("task.getDueDate() = " + task.getDueDate());
//        Weekly daily = new Weekly(1, 1, 1, false, new TreeSet<>(List.of(DayOfWeek.SUNDAY)));
//        daily.setTaskID(task.getId());
//
//        LocalDate adjustGap = adjustGap(daily.getType(), task.getDueDate(), daily.getGap());
//        System.out.println("adjustGap = " + adjustGap);
//        LocalDate adjustWeekDay = adjustDays(adjustGap, daily.getDaysOfWeek());
//        System.out.println("nextDay = " + adjustWeekDay);
//    }
//
//    @Test
//    void verify_rec_monthly() {
//        ToDoTask task = new ToDoTask(1, "Practice on my guitar", LocalDate.now().minusWeeks(1));
//        System.out.println("task.getDueDate() = " + task.getDueDate());
//        Monthly daily = new Monthly(1, 1, 1, new TreeSet<>(List.of(DayOfWeek.TUESDAY)));
//        daily.setTaskID(task.getId());
//
//        LocalDate adjustGap = adjustGap(daily.getType(), task.getDueDate(), daily.getGap());
//        System.out.println("adjustGap = " + adjustGap);
//        LocalDate adjustWeekDay = adjustDays(adjustGap, daily.getDaysOfWeek());
//        System.out.println("nextDay = " + adjustWeekDay);
//    }
//
//    @Test
//    void verify_rec_yearly() {
//        ToDoTask task = new ToDoTask(1, "Practice on my guitar", LocalDate.now());
//        System.out.println("task.getDueDate() = " + task.getDueDate());
//        Yearly daily = new Yearly(1, 1, 1, new TreeSet<>(List.of(DayOfWeek.TUESDAY)));
//        daily.setTaskID(task.getId());
//
//        LocalDate adjustGap = adjustGap(daily.getType(), task.getDueDate(), daily.getGap());
//        System.out.println("adjustGap = " + adjustGap);
//        LocalDate adjustWeekDay = adjustDays(adjustGap, daily.getDaysOfWeek());
//        System.out.println("nextDay = " + adjustWeekDay);
//    }
//
//
//    private LocalDate adjustGap(RecurrenceType type, LocalDate date, int gap) {
//        System.out.println("type = " + date);
//        switch (type) {
//            case DAILY, WEEKDAYS -> date = date.plusDays(gap);
//            case WEEKLY -> date = date.plusWeeks(gap);
//            case MONTHLY ->  date = date.plusMonths(gap);
//            case YEARLY -> date = date.plusYears(gap);
//        }
//        return date;
//    }
//
//    @Test void test_time_stamp() {
//
//    }
//
//    private LocalDate adjustDays(LocalDate date, Set<DayOfWeek> dayOfWeeks) {
//        if (dayOfWeeks.contains(date.getDayOfWeek())) {
//            return date;
//        } else {
//            return adjustDays(date.plusDays(1), dayOfWeeks);
//        }
//    }
//
//}
