/*
 * This source file was generated by the Gradle 'init' task
 */
package todo;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

import io.github.gleidsonmt.todo.bd.DatabaseConnection;
import io.github.gleidsonmt.todo.global.Repository;

class AppTest {

    @Test
    void appHasConnection() {
        assertNotNull(new DatabaseConnection(), "app has a database connection setup");
        DatabaseConnection classUnderTest = new DatabaseConnection();

        assertTrue(classUnderTest.connect(), "app should have a database connection");

    }

    @Test
    void subText() {
        Repository repo = new Repository();

        repo.loadData();

        assertTrue(!repo.getData().isEmpty());
    }
}
