package io.github.gleidsonmt.todo.view.presentation;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.yaml.snakeyaml.LoaderOptions;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.constructor.Constructor;
import org.yaml.snakeyaml.inspector.TagInspector;

import io.github.gleidsonmt.todo.App;
import javafx.animation.KeyFrame;
import javafx.animation.KeyValue;
import javafx.animation.Timeline;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.effect.ColorAdjust;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.scene.text.TextAlignment;
import javafx.scene.text.TextFlow;
import javafx.util.Duration;

/**
 * Description:
 *
 * @author Gleidson Neves da Silveira | <gleidisonmt@gmail.com>
 * Created On: Feb 23, 2026
 * <p>
 * Version History: Initial version
 */
public class Presentation extends StackPane {

    private final Text legend;
    private final VBox contentBox;
    private final Text title;
    private final TextFlow mainTitleFlow;
    private final Text mainTitle;
    private final TextFlow contentFlow;
    private final Text contentText;

    public Presentation() {
        this.legend = createLegend();
        this.contentBox = createContentBox();
        this.title = createText("JavaFx ToDo!", "text-22 font-instagram-headline");
        this.mainTitle = createText("text-48 font-instagram-bold");
        this.mainTitleFlow = createFlow(mainTitle);
        this.contentText = createText("text-22 font-instagram");
        this.contentFlow = createFlow(contentText);

        this.contentFlow.setPrefHeight(200);
        this.contentFlow.setPrefWidth(100);
        configLayout();

        setMaxWidth(400);
    }

    private void configLayout() {
        contentBox.getChildren().addAll(title, mainTitleFlow, contentFlow);
        this.getChildren().addAll(createBackground(), contentBox, legend);
    }

    private VBox createContentBox() {
        VBox box = new VBox();

        box.setAlignment(Pos.CENTER);
        box.setSpacing(10);

        StackPane.setMargin(box, new Insets(10));
        return box;
    }

    private Text createLegend() {
        var legendText = createText("text-14 font-instagram");
        legendText.setText("Generated by IA");
        StackPane.setAlignment(legendText, Pos.BOTTOM_CENTER);
        StackPane.setMargin(legendText, new Insets(0, 0, 20, 0));
        return legendText;
    }

    private TextFlow createFlow(Text text) {
        TextFlow flow = new TextFlow(text);
        flow.setTextAlignment(TextAlignment.CENTER);
        return flow;
    }

    private Text createText(String classes) {
        return createText("", classes);
    }

    private Text createText(String _text, String classes) {
        var text = new Text(_text);

        text.getStyleClass().addAll(Arrays.asList("text-white ".split(" ")));
        text.getStyleClass().addAll(Arrays.asList(classes.split(" ")));
        return text;
    }

    int time = 0;

    private Region createBackground() {
        Region region = new Region();
        region.getStyleClass().add("ativo");
        region.setPrefSize(800, USE_PREF_SIZE);

        ColorAdjust colorAdjust = new ColorAdjust();

        region.setEffect(colorAdjust);

        Timeline timeline = new Timeline();

        Platform.runLater(() -> {

            try {

                timeline.getKeyFrames().addAll(new KeyFrame(Duration.ZERO, new KeyValue(colorAdjust.hueProperty(), -1)),
                        new KeyFrame(Duration.seconds(10), new KeyValue(colorAdjust.hueProperty(), 0.1)),
                        new KeyFrame(Duration.seconds(20), new KeyValue(colorAdjust.hueProperty(), 0.5)),
                        new KeyFrame(Duration.seconds(30), new KeyValue(colorAdjust.hueProperty(), 0.75)));

                parseYaml().forEach(info -> {
                    createAnimations(timeline, info);
                });
                // time = 0;

            } catch (IOException e) {
                // TODO Auto-generated catch block
            }

            timeline.setCycleCount(Timeline.INDEFINITE);
            // timeline.setAutoReverse(true);
            timeline.play();

        });

        return region;
    }

    private void createAnimations(Timeline timeline, InfoContent info) {

        timeline.getKeyFrames().addAll(Arrays.asList(createKeyFrames(info.getTitle(), Duration.millis(time))));
        timeline.getKeyFrames().add(new KeyFrame(Duration.millis(time), new KeyValue(contentText.textProperty(), "")));

        time += info.getTitle().length() * 100;

        timeline.getKeyFrames().addAll(
                new KeyFrame(Duration.millis(time += 1000), new KeyValue(mainTitle.textProperty(), info.getTitle())),
                new KeyFrame(Duration.millis(time -= 1000),
                        new KeyValue(contentText.textProperty(), info.getContent())));

        time += 5000;
    }

    public List<InfoContent> parseYaml() throws IOException {
        var loaderoptions = new LoaderOptions();
        TagInspector taginspector = tag -> tag.getClassName().equals(InfoContent.class.getName());
        loaderoptions.setTagInspector(taginspector);

        Yaml yaml = new Yaml(new Constructor(InfoContent.class, loaderoptions));

        InputStream inputStream = App.class.getResourceAsStream("yaml/home_info.yml");

        List<InfoContent> members = new ArrayList<>();
        var load = yaml.loadAll(inputStream);
        while (load.iterator().hasNext()) {
            members.add((InfoContent) load.iterator().next());
        }
        return members;
    }

    private KeyFrame[] createKeyFrames(String text, Duration duration) {
        KeyFrame[] frames = new KeyFrame[text.length()];
        for (int i = 0; i < text.length(); i++) {
            final int index = i;
            frames[i] = new KeyFrame(duration.add(Duration.millis((i * 80))),
                    new KeyValue(this.mainTitle.textProperty(), text.substring(0, index + 1)));
        }
        return frames;
    }

}
